title: pyDPM doc
lang: en
description: Documents for pyDPM: A python library focuses on constructing deep probabilistic models on GPU.

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock